fundraising/urls.py
from django.urls import include, path

from .views import (
    RecipeBookSubmissionCreateView, RecipeBookSubmissionDetailView, RecipeBookSubmissionUpdateView, 
    update_form_fields, method_char_count, profile_caption_char_count, submitted_recipes, user_bids, notify_winners,
    notify_auction_item_donor, notify_auction_item_winner, toggle_withdrawn_bid
)
app_name = "fundraising"
urlpatterns = [
    path(
        "recipe-book/contribution/add/", 
        RecipeBookSubmissionCreateView.as_view(), 
        name="recipe_book_contribution_add"
    ),
    path(
        "recipe-book/contribution/<str:pk>/", 
        RecipeBookSubmissionDetailView.as_view(), 
        name="recipe_book_contribution_detail"
    ),
    path(
        "recipe-book/contribution/<str:pk>/edit/", 
        RecipeBookSubmissionUpdateView.as_view(), 
        name="recipe_book_contribution_edit"
    ),
    path(
        "bids/<slug:auction_slug>", user_bids, name="user_bids"
    ),
    path(
        "recipe-book/recipes", submitted_recipes, name="submitted_recipes"
    ),
    path(
        "update-form-fields", update_form_fields, name="update_form_fields"
    ),
    path(
        "count/method", method_char_count, name="method_char_count"
    ),
    path(
        "count/profile", profile_caption_char_count, name="profile_caption_char_count"
    ),
    path(
        "auction/<pk>/notify-winners", notify_winners, name="notify_auction_winners", 
    ),
    path(
        "auction/item/<pk>/notify-winner", notify_auction_item_winner, name="notify_auction_item_winner", 
    ),
    path(
        "auction/item/<pk>/notify-donor", notify_auction_item_donor, name="notify_auction_item_donor", 
    ),
    path(
        "auction/bid/<pk>/withdraw", toggle_withdrawn_bid, name="toggle_withdrawn_bid", 
    )

]

pins/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views
from home import orders_urls
from home import views as home_views
from fundraising import urls

urlpatterns = [
    path("", include('allauth.urls')),
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("orders/", include(orders_urls)),
    path("fundraising/", include(urls)),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path("payments/", include("payments.urls")),
    path(
        "submitted-form/<str:reference>/access-request/", 
        home_views.pdf_form_token_request, 
        name="pdf_form_token_request"
    ),
    path(
        "submitted-form/<str:reference>/", 
        home_views.pdf_form_detail, 
        name="pdf_form_detail"
    ),
    path(
        "submitted-form/<int:pk>/download/", 
        home_views.pdf_form_download, 
        name="pdf_form_download"
    ),
    path(
        "merchandise-information/",
        home_views.merch_info,
        name="merch_info"
    )
]


if settings.DEBUG or settings.TESTING:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += (path(r'django-admin/django-ses/', include('django_ses.urls')),)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

fundraising/views.py
from typing import Any
from django import http
from django.conf import settings
from django.core.mail import send_mail
from wagtail.admin.mail import send_mail as wagtail_send_mail
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.views.decorators.http import require_POST

from django.urls import reverse
from django.template.response import TemplateResponse
from django.template.context_processors import csrf
from django.views.generic import CreateView, DetailView, UpdateView

from crispy_forms.utils import render_crispy_form
from payments.utils import get_paypal_form


from payments.utils import signature

from .forms import RecipeBookContrbutionForm, RecipeBookContrbutionEditForm
from .models import RecipeBookSubmission, Bid, Auction, AuctionItem


class RecipeBookSubmissionCreateView(CreateView):

    model = RecipeBookSubmission
    template_name = "fundraising/recipe_book_contribution_add_edit.html"
    form_class = RecipeBookContrbutionForm

    def form_valid(self, form):
        # submit form, create unpaid submission
        # go to detail page with paypal button
        submission = form.save()
        self.send_submission_email(submission)
        return redirect(submission)

    def form_invalid(self, form):
        form = RecipeBookContrbutionForm(
            data=self.request.POST, files=self.request.FILES, page_type=self.request.POST.get("page_type")
        )
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["new"] = True
        return context
    
    def send_submission_email(self, submission):
        title = f"Recipe title: {submission.title}\n" if submission.page_type != "photo" else ""
        send_mail(
            "Recipe book contribution received!",
            (
                f"Thank you for your contribution!\n{title}\n"
                f"You can view/edit your submission at https://{self.request.get_host()}{submission.get_absolute_url()}.\n"
                f"To edit your submission details you will need your passcode: {submission.code}\n\n"
                "If you have not already made your payment, you can find a PayPal link there too.\n\n"
                "Thank you for supporting Podencos In Need (PINS) <3."
            ),
            settings.DEFAULT_FROM_EMAIL,
            [submission.email],
            fail_silently=False,
        )
        send_mail(
            "A new recipe book contribution has been received",
            (
                f"From: {submission.name}\n"
                f"Page type: {submission.page_type_verbose()}\n"
                f"{title}"
            ),
            settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_ADMIN_EMAIL],
            fail_silently=False,
        )
    

class RecipeBookSubmissionDetailView(DetailView):

    model = RecipeBookSubmission
    template_name = "fundraising/recipe_book_contribution_detail.html"
    context_object_name = "submission"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        submission = context["submission"]
        
        if not submission.paid:
            context["paypal_form"] = get_paypal_form(
                request=self.request,
                amount=submission.cost, 
                item_name=f"Recipe Book submission: {submission.page_type_verbose()}",
                reference=submission.reference
            )
        return context


class RecipeBookSubmissionUpdateView(UpdateView):

    model = RecipeBookSubmission
    template_name = "fundraising/recipe_book_contribution_add_edit.html"
    context_object_name = "submission"
    form_class = RecipeBookContrbutionEditForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.processing or obj.complete:
            return redirect(obj)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["new"] = False
        return context


def update_form_fields(request):
    ctx = {}
    ctx.update(csrf(request))
    initial = {k: request.POST.get(k) for k in request.POST if k not in ["profile_image", "photo"]}
    form = RecipeBookContrbutionForm(initial=initial, page_type=request.POST.get("page_type"))
    return HttpResponse(render_crispy_form(form, context=ctx))


def char_count(request, fieldname):
    fieldcount = len(request.GET.get(fieldname))
    max_count = int(request.GET.get("max"))
    count_str = f"Character count: {str(fieldcount)}"
    if fieldcount >= max_count:
        count_str = f"<strong class='text-danger'>{count_str}</strong>"
    return HttpResponse(count_str)


def method_char_count(request):
    return char_count(request, "method")


def profile_caption_char_count(request):
    return char_count(request, "profile_caption")


def submitted_recipes(request):
    dog_recipes = RecipeBookSubmission.objects.filter(category="dog").order_by("title").values_list("title", flat=True)
    human_recipes = RecipeBookSubmission.objects.filter(category="human").order_by("title").values_list("title", flat=True)
    return TemplateResponse(
        request, 
        "fundraising/recipe_list.html", 
        {"dog_recipes": dog_recipes, "human_recipes": human_recipes}
    )


def user_bids(request, auction_slug):
    auction = get_object_or_404(Auction, slug=auction_slug)
    auction_item_ids = auction.get_children().specific().values_list('id', flat=True)
    bids = request.user.bids.filter(auction_item__id__in=auction_item_ids)
    return TemplateResponse(
        request, 
        "fundraising/user_bids.html", 
        {"auction": auction, "bids": bids}
    )


def withdraw_bid(request, bid_id):
    # called via htmx from admin bids page
    bid = get_object_or_404(Bid, pk=bid_id)
    bid.withdrawn = True
    bid.save()
    auction_item = bid.auction_item

    send_mail(
        "PINS Auction: Your bid has been withdrawn",
        (
            "An admin has withdrawn your bid on the following PINS auction item:\n"
            f"{auction_item.title} ({auction_item.get_parent().title})\n\n"
        ),
        [bid.user.email],
        settings.DEFAULT_FROM_EMAIL,
        reply_to=[settings.DEFAULT_ADMIN_EMAIL],
    )

    resp = HttpResponse()
    resp.headers["HX-Refresh"] = "true"
    return resp


@require_POST
def toggle_withdrawn_bid(request, pk):
    bid = get_object_or_404(Bid, pk=pk)
    next_url = request.GET.get("next", reverse("auction_item_result", args=(bid.auction_item.id,)))
    new_status = bid.toggle_withdrawn(request)
    if new_status:
        messages.success(request, "Bid has been withdrawn")
    else:
        messages.success(request, "Bid has been reinstated")
    return redirect(next_url)


@require_POST
def notify_auction_item_donor(request, pk):
    auction_item = get_object_or_404(AuctionItem, pk=pk)
    auction = auction_item.get_parent().specific
    next_url = request.GET.get("next", reverse("auction_item_result", args=(pk,)))
    if not auction.is_closed():
        messages.error(request, "Cannot notify donor; auction is not yet closed")
    else:
        notified = auction_item.notify_donor(request)
        if notified:
            messages.success(request, "Donor has been notified by email")
    return redirect(next_url)


@require_POST
def notify_auction_item_winner(request, pk):
    auction_item = get_object_or_404(AuctionItem, pk=pk)
    auction = auction_item.get_parent().specific
    next_url = request.GET.get("next", reverse("auction_item_result", args=(pk,)))
    if not auction.is_closed():
        messages.error(request, "Cannot notify winners; auction is not yet closed")
    else:
        notified = auction_item.notify_winner(request)
        if notified:
            messages.success(request, "Winner has been notified by email")
    return redirect(next_url)


@require_POST
def notify_winners(request, pk):
    # called from admin auction detail page
    auction = get_object_or_404(Auction, pk=pk)
    if not auction.is_closed():
        messages.error(request, "Cannot notify winners; auction is not yet closed")
    else:
        auction_items = auction.get_children().specific()
        notified_count = 0
        for auction_item in auction_items:
            notified = auction_item.notify_winner(request)
            if notified:
                notified_count += 1
        messages.success(request, f"{notified_count} winners have been notified")
    return redirect(reverse("auction_detail", args=(pk,)))

fundraising/templates/fundraising/admin/includes/bid.html
<dt>Bidder name</dt>
<dd>{{ bid.user.first_name }} {{ bid.user.last_name }} ({{ bid.user.username }})</dd>

<dt>Bidder email</dt>
<dd>{{ bid.user.email }}</dd>

<dt>Bid Amount</dt>
<dd>£{{ bid.amount }}</dd>

<dt>Total due (incl. p&p)</dt>
<dd>£{{ auction_item.total_due }}</dd>

<dt>Shipping details</dt>
<dd>{{ bid.name }}<br/>
{{ bid.address_line_1 }}<br/>
{% if bid.address_line_2 %}{{ bid.address_line_2 }}<br/>{% endif %}
{% if bid.address_line_3 %}{{ bid.address_line_3 }}<br/>{% endif %}
{{ bid.town_city }}<br/>
{{ bid.county }}<br/>
{{ bid.postcode }}<br/>

fundraising/templates/fundraising/admin/includes/change_category_list_items_with_no_access.html
{% extends 'wagtailadmin/bulk_actions/confirmation/list_items_with_no_access.html' %}
{% load i18n %}

{% block per_item %}
    {% if item.can_edit %}
    <a href="{% url 'wagtailadmin_pages:edit' item.item.id %}" target="_blank" rel="noreferrer">{{ item.item.title }}</a>
    {% else %}
    {{ item.item.title }}
    {% endif %}
{% endblock per_item %}

fundraising/templates/fundraising/admin/includes/winning_bid_buttons.html
{% if bid.is_winner %}
    {% if bid.winner_notified %}
        <span class="font-success">The bidder has been notified of their win and has been sent payment information.</span>
    {% else %}
        <span class="font-danger">The bidder has not yet been notified of their win.</span>
        <br/><br/>
        <form action="{{ bid.auction_item.notify_winner_url }}?next={{ request.build_absolute_uri}}" method="POST">
            {% csrf_token %}
            <label>Email bidder with confirmation of win and request for payment.</label>
            <input type="submit" value="Notify winner" class="button button-success ml-4" {% if not auction.is_closed %}disabled{% endif %} />
        </form>
    {% endif %}
    <br/>
    {% if bid.donor_notified %}
        <span class="font-success">The donor has been notified of the win and has been sent shipping information.</span>
    {% elif bid.winner_notified %}
        <span class="font-danger">The donor has not yet been notified of the win.</span>
        <br/><br/>
        <form action="{{ bid.auction_item.notify_donor_url }}?next={{ request.build_absolute_uri}}" method="POST">
            {% csrf_token %}
            <div class="form-group">
            <input id="confirm_payment" type="checkbox" required=True />
            <label for="confirm_payment">Tick to confirm payment has been received from the winning bidder.</label>
            </div>
            <label>Email donor with confirmation of win and shipping information.</label>
            <input type="submit" value="Notify donor" class="button button-success ml-4" {% if not auction.is_closed %}disabled{% endif %} />
        </form>
    {% endif %}
{% endif%}
<hr/>

fundraising/templates/fundraising/admin/includes/withdraw_button.html
{% if auction.is_closed %}
    <h3>
        <svg class="icon icon-warning icon-auction font-danger" aria-hidden="true"><use href="#icon-warning"></use></svg>

        {% if bid.withdrawn %}Reinstate{% else %}Withdraw{% endif %} this bid

        <svg class="icon icon-warning icon-auction font-danger" aria-hidden="true"><use href="#icon-warning"></use></svg>
    </h3>
    <div class="font-danger">
        {% if bid.withdrawn %}
            Warning: this will reinstate the bid. If this is the highest amount, it will replace the current winning bid. Be sure
            that this will not cause conflicts with the current winner.
        {% elif winning_bid %}
            Warning: this will withdraw the winning bid. The next highest bid will become the winning bid, and you will be able to
            notify the new winner.
        {% else %}
            Warning: this will withdraw the bid. If this is the current winning bid, the next highest bid will become the new winning bid.
            If the donor has already been notified of the winner, be sure to contact them to ensure they have not sent the item out already.
        {% endif %}
    </div>
    <form action="{% url 'fundraising:toggle_withdrawn_bid' bid.id %}?next={{ request.build_absolute_uri }}" method="POST">
        {% csrf_token %}
        <div>
        <input id="confirm" type="checkbox" required=True />
        <label for="confirm">Tick to confirm you wish to {% if bid.withdrawn %}reinstate{% else %}withdraw{% endif %} this bid</label>
        </div><br/>
        <input type="submit" value="{% if bid.withdrawn %}Reinstate{% else %}Withdraw{% endif %} this bid" class="button serious ml-4" />
    </form>
{% endif %}